name: build

on:
  push:

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dotnet build
      run: cd Greeter.Service && dotnet build

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dotnet build
      run: cd Greeter.Client && dotnet build

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dotnet test
      run: cd Greeter.Test && dotnet test
