name: build

on:
  push:

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dotnet build
      run: cd Greeter.Service && dotnet build

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dotnet build
      run: cd Greeter.Client && dotnet build

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dotnet test
      run: cd Greeter.Test && dotnet test

  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build -t greeter -f Greeter.Service/Dockerfile .
    - name: docker run
      run: docker run --rm -d --name greeter -p 5001:443 greeter
    - name: dotnet run 
      run: cd Greeter.Client && dotnet run
    - name: docker stop
      run: docker stop greeter
