name: build

on:
  push:

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: dotnet publish '${{ env.VERSION }}'
      run: dotnet publish -c Release Greeter.Service

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: dotnet publish '${{ env.VERSION }}'
      run: dotnet publish -c Release Greeter.Client

  dotnet-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: dotnet test '${{ env.VERSION }}'
      run: dotnet test -c Release Greeter.Test

  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: docker build '${{ env.VERSION }}'
      run: docker build -t greeter-service -f Greeter.Service/Dockerfile .
    - name: docker run
      run: docker run --rm -d --name greeter-service -p 5001:443 greeter-service
    - name: dotnet run 
      run: |
        cd Greeter.Client
        # First call to service is slower due to AutoMapper initialisation
        dotnet run -c Release > /dev/null
        # For proper gRPC timing in service logs
        dotnet run --no-build -c Release
    - name: docker logs
      run: docker logs greeter-service
    - name: docker stop
      run: docker stop greeter-service

  bench-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: Conversion benchmarks '${{ env.VERSION }}'
      run: |
        cd Greeter.Bench
        dotnet run -c Release

  bench-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version
      uses: EduardSergeev/project-version-action@main
      with:
        time-zone: Australia/Sydney
        version-file: properties/Global.props
        version-stub: '0.0.0.0'      
    - name: Conversion benchmarks '${{ env.VERSION }}'
      run: |
        cd Greeter.Bench
        dotnet run -c Release
